SchoolWeb/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Domain.Entities;
using School.Domain.Enums;
using School.Infrastructure.Repositories;
using SchoolWeb.ViewModels;
using System.Diagnostics;

namespace SchoolWeb.Controllers
{
	public class EnrollmentController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public EnrollmentController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Create()
		{
			List<Student> students = _unitOfWork.StudentRepository.GetAll().ToList();
			List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();

			CreateEnrollmentViewModel createEnrollmentViewModel = new CreateEnrollmentViewModel
			{
				StudentLists = students.Select(student => new SelectListItem { Text = $"{student.Name} {student.LastName}", Value = student.Id.ToString() }).ToList(),
				GradeLists = grades.Select(grade => new SelectListItem { Text = grade.Name, Value = grade.Id.ToString() }).ToList(),
			};

			return View(createEnrollmentViewModel);
		}

		public IActionResult Edit(int id)
		{
			var enrollment = _unitOfWork.EnrollmentRepository.Get(enrollment => enrollment.Id == id);

			if(enrollment is null)
			{
					TempData["error"] = "Enrollment was not found";
					return RedirectToAction("Index");
			}

			List<Student> students = _unitOfWork.StudentRepository.GetAll().ToList();
			List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();
			EditEnrollmentViewModel editEnrollmentViewModel = new EditEnrollmentViewModel
			{
				StudentLists = students.Select(student => new SelectListItem { Text = $"{student.Name} {student.LastName}", Value = student.Id.ToString()}).ToList(),
				GradeLists = grades.Select(grade => new SelectListItem { Text = grade.Name, Value = grade.Id.ToString() }).ToList(),
				GradeId = enrollment.GradeId,
				EnrollmentStatus = enrollment.EnrollmentStatus,
			};

			return View(editEnrollmentViewModel);
		}

		public IActionResult Delete(int id)
		{
			var enrollment = _unitOfWork.EnrollmentRepository.Get(enrollment => enrollment.Id == id, "Student,Grade");

			if(enrollment is null)
			{
				TempData["error"] = "Enrollment was not found";
				return RedirectToAction("Index");
			}

			return View(enrollment);
		}

		[HttpPost]
		public IActionResult Create(CreateEnrollmentViewModel createEnrollmentViewModel)
		{
			try
			{
				if(ModelState.IsValid)
				{
					var studentEnrollments = _unitOfWork.StudentRepository.Get(student => student.Id == createEnrollmentViewModel.StudentId, "Enrollments");

					if (studentEnrollments.Enrollments.Any(student => student.EnrollmentStatus != EnrollmentStatus.PASSED))
					{
						TempData["error"] = "Student is already enrolled in other grade";
						return RedirectToAction("Index");
					}

					var newStundentEnrollment = new Enrollment
					{
						StudentId = createEnrollmentViewModel.StudentId,
						GradeId = createEnrollmentViewModel.GradeId,
						EnrollmentStatus = EnrollmentStatus.CURRENTLY_ENROLLED,
					};

					_unitOfWork.EnrollmentRepository.Add(newStundentEnrollment);
					_unitOfWork.Save();
					TempData["success"] = "Enrollment created successfully";
					return RedirectToAction("Index");
				}
			}catch (Exception ex)
			{
				TempData["error"] = "Something went wrong while creating the register";
				return RedirectToAction("Index");
			}
			return View(createEnrollmentViewModel);
		}

		[HttpPost]
		public IActionResult Edit(EditEnrollmentViewModel enrollmentViewModel)
		{
			try
			{
				if(ModelState.IsValid)
				{
					var enrollment = _unitOfWork.EnrollmentRepository.Get(enrollment => enrollment.Id == enrollmentViewModel.Id);
					if(enrollment is null)
					{
						TempData["error"] = "Enrollment was not found";
						return RedirectToAction("Index");
					}

					var studentEnrollments = _unitOfWork.StudentRepository.Get(student => student.Id == enrollment.StudentId, "Enrollments");

					var checkPassedGrades = studentEnrollments.Enrollments.
						Where(enrollment => enrollment.Id != enrollmentViewModel.Id).ToList();
					
					if(checkPassedGrades.Any(student => student.EnrollmentStatus != EnrollmentStatus.PASSED))
					{
						TempData["error"] = "You cannot update the state of a course while other course is not in passed state";
						return RedirectToAction("Index");
					}

					enrollment.GradeId = enrollmentViewModel.GradeId;
					enrollment.EnrollmentStatus = enrollmentViewModel.EnrollmentStatus;

					_unitOfWork.EnrollmentRepository.Update(enrollment);
					_unitOfWork.Save();

					TempData["success"] = "Grade updated successfully";

					return RedirectToAction("Index");

				}
			}catch (Exception ex)
			{
				TempData["error"] = "Something went wrong while updating the register";
				return RedirectToAction("Index");
			}

			return View(enrollmentViewModel);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteEnrollment(int? id)
		{
			try
			{
				var enrollment = _unitOfWork.EnrollmentRepository.Get(enrollment => enrollment.Id == id);
				if (enrollment is null)
				{
					TempData["error"] = "Enrollment was not found";
					return RedirectToAction("Index");
				}

				_unitOfWork.EnrollmentRepository.Remove(enrollment);
				_unitOfWork.Save();
				TempData["success"] = "Enrollment deleted successfully";
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData["error"] = "Something failed while deleting enrollment";
				return RedirectToAction("Index");
			}
		}

		#region
		[HttpGet]
		public IActionResult GetAll()
		{
			List<Enrollment> enrollments = _unitOfWork.EnrollmentRepository.GetAll("Student,Grade").ToList();
			return Json(new { data = enrollments });
		}
		#endregion
	}
}

SchoolWeb/Views/Enrollment/Create.cshtml
@using School.Domain.Enums
@model CreateEnrollmentViewModel

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-light-subtle bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h3 class="text-primary">Create Enrollment</h3>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" class="row">
			<div class="border p-3">
				<div class="row mb-4">
					<div class="form-floating py-2 col-12 col-md-6">
						<select asp-for="StudentId" asp-items="@Model.StudentLists" class="form-select border-0 shadow">
							<option disabled selected>--Select student--</option>
						</select>
						<label class="ms-1">Student</label>
						<span asp-validation-for="StudentId" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12 col-md-6">
						<select asp-for="GradeId" asp-items="@Model.GradeLists" class="form-select border-0 shadow">
							<option disabled selected>--Select Grade--</option>
						</select>
						<label class="ms-1">Grade</label>
						<span asp-validation-for="GradeId" class="text-danger"></span>
					</div>
				</div>
@* 				<div class="form-floating py-2 col-12">
					<select asp-for="EnrollmentStatus" asp-items="Html.GetEnumSelectList(typeof(EnrollmentStatus))" class="form-select border-0 shadow">
					</select>
					<label class="ms-1">Enrollment status</label>
					<span asp-validation-for="EnrollmentStatus" class="text-danger"></span>
				</div> *@
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary bg-transparent text-primary form-control">Back to list</a>
					</div>
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-primary form-control">Create</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

SchoolWeb/Views/Enrollment/Delete.cshtml
@using School.Domain.Enums
@model Enrollment

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-light-subtle bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h3 class="text-primary">Delete Enrollment</h3>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" class="row">
			<div class="border p-3">
				<input asp-for="Id" hidden />
				<div class="row mb-4">
					<input type="hidden" asp-for="@Model.Id" />
					<div class="form-floating py-2 col-12">
						<p class="form-control border-0 shadow" disabled>
							@Model.Grade.Name
						</p>
						<label class="ms-1">Grade</label>
						<span asp-validation-for="GradeId" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<p class="form-control border-0 shadow" disabled>
							@Model.EnrollmentStatus.ToString()
						</p>
						<label class="ms-1">Enrollment status</label>
						<span asp-validation-for="EnrollmentStatus" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<p class="form-control border-0 shadow" disabled>
							@Model.Student.Name @Model.Student.LastName
						</p>
						<label class="ms-1">Student</label>
						<span asp-validation-for="EnrollmentStatus" class="text-danger"></span>
					</div>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary bg-transparent text-primary form-control">Back to list</a>
					</div>
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-primary form-control">Delete</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

SchoolWeb/Views/Enrollment/Edit.cshtml
@using School.Domain.Enums
@model EditEnrollmentViewModel

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-light-subtle bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h3 class="text-primary">Update Enrollment</h3>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" class="row">
			<div class="border p-3">
				<input asp-for="Id" hidden />
				<div class="row mb-4">
					<div class="form-floating py-2 col-12">
						<select asp-for="GradeId" asp-items="@Model.GradeLists" class="form-select border-0 shadow">
							<option disabled selected>--Select Grade--</option>
						</select>
						<label class="ms-1">Grade</label>
						<span asp-validation-for="GradeId" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<select asp-for="EnrollmentStatus" asp-items="Html.GetEnumSelectList(typeof(EnrollmentStatus))" class="form-select border-0 shadow">
						</select>
						<label class="ms-1">Enrollment status</label>
						<span asp-validation-for="EnrollmentStatus" class="text-danger"></span>
					</div>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary bg-transparent text-primary form-control">Back to list</a>
					</div>
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-primary form-control">Update</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

SchoolWeb/Views/Enrollment/Index.cshtml
@model List<Enrollment>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-primary">Enrollment Lists</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-12 text-end">
				<a asp-controller="Enrollment" asp-action="Create" class="btn btn-primary">
					<i class="bi bi-plus-circle"></i>  CREATE NEW ENROLLMENT
				</a>
			</div>
		</div>
		<table id="example" class="table table-bordered table-striped">
			<thead>
				<tr class="text-center">
					<th>ID</th>
					<th>STUDENT</th>
					<th>GRADE</th>
					<th>STATUS</th>
					<th></th>
				</tr>
			</thead>
		</table>
	</div>
</div>

@section Scripts {
	<script src="~/js/enrollment.js"></script>
}