SchoolWeb/Controllers/GradeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using School.Domain.Entities;
using School.Infrastructure.Repositories;
using School.Infrastructure.Services;
using School.Utility;

namespace SchoolWeb.Controllers
{
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class GradeController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

        public GradeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
		{
			List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();

			return View(grades);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Grade grade)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_unitOfWork.GradeRepository.Add(grade);
					_unitOfWork.Save();
					TempData["success"] = "Grade created successfully";
					return RedirectToAction("Index");
				}
			}
			catch (Exception)
			{
				TempData["error"] = "Error while creating register";
				return RedirectToAction("Index");
			}
			return View();
		}

		public IActionResult Edit(int? id)
		{
			if(id is null || id <= 0)
			{
				return NotFound();
			}

			var grade = _unitOfWork.GradeRepository.Get(grade => grade.Id == id);

			if(grade is null)
			{
				return NotFound();
			}

			return View(grade);
		}

		[HttpPost]
		public IActionResult Edit(Grade grade)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_unitOfWork.GradeRepository.Update(grade);
					_unitOfWork.Save();
					TempData["success"] = "Grade updated successfully";
					return RedirectToAction("Index");
				}
			}
			catch (Exception)
			{
				TempData["error"] = "Something failed while updateding register";
				return RedirectToAction("Index");
			}

			return View();
		}

		public IActionResult Delete(int? id)
		{
			if(id is null || id <= 0)
			{
				return NotFound();
			}

			var grade = _unitOfWork.GradeRepository.Get(grade => grade.Id == id);

			if(grade is null)
			{
				return NotFound();
			}

			return View(grade);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteGrade(int? id)
		{
			var grade = _unitOfWork.GradeRepository.Get(grade => grade.Id == id);
			if(grade is null)
			{
				return NotFound();
			}
			_unitOfWork.GradeRepository.Remove(grade);
			_unitOfWork.Save();
			TempData["success"] = "Grade deleted successfully";
			return RedirectToAction("Index");
		}
	}
}

SchoolWeb/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using NuGet.DependencyResolver;
using School.Domain.Entities;
using School.Infrastructure.Repositories;
using School.Infrastructure.Services;
using School.Utility;
using SchoolWeb.ViewModels;
using System.Numerics;

namespace SchoolWeb.Controllers
{
	[Authorize(Roles = StaticDetails.ROLE_ADMIN)]
	public class StudentController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly ICloudinaryService _cloudinaryService;

		public StudentController(IUnitOfWork unitOfWork, ICloudinaryService cloudinaryService)
		{
			_unitOfWork = unitOfWork;
			_cloudinaryService = cloudinaryService;
		}

		public IActionResult Index()
		{
			List<Student> students = _unitOfWork.StudentRepository.GetAll().ToList();
			return View(students);
		}

		public IActionResult Create()
		{
			return View();
		}

		public IActionResult Detail(int id)
		{
            if (id <= 0)
            {
                TempData["error"] = "Student not found";
                return RedirectToAction("Index");
            }
            var student = _unitOfWork.StudentRepository.Get(s => s.Id == id);

			if(student is null)
			{
                TempData["error"] = "Student not found";
                return RedirectToAction("Index");
            }

			return View(student);
		}

		public IActionResult Edit(int id)
		{
			if (id <= 0)
			{
				TempData["error"] = "Teacher not found";
				return RedirectToAction("Index");
			}
			var student = _unitOfWork.StudentRepository.Get(s =>s.Id == id);


			if (student is null)
			{
				TempData["error"] = "Student not found";
				return RedirectToAction("Index");
			}

			var editStudentViewModel = new EditStudentViewModel
			{
				Id = student.Id,
				DateOfBirth = student.DateOfBirth,
				Email = student.Email,
				LastName = student.LastName,
				Name = student.Name,
				Phone = student.Phone
			};

			return View(editStudentViewModel);
		}

		public IActionResult Delete(int id)
		{
			var student = _unitOfWork.StudentRepository.Get(s => s.Id==id);
			if (student is null)
			{
				TempData["error"] = "Student not found";
				return RedirectToAction("Index");
			}

			return View(student);

		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateStudentViewModel createStudentViewModel)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var uploadImage = await _cloudinaryService.AddPhoto(createStudentViewModel.Image);

					var newStudent = new Student
					{
						Name = createStudentViewModel.Name,
						LastName = createStudentViewModel.LastName,
						Age = DateTime.Now.Year - createStudentViewModel.DateOfBirth.Year,
						DateOfBirth = createStudentViewModel.DateOfBirth,
						Email = createStudentViewModel.Email,
						Phone = createStudentViewModel.Phone,
						Image = uploadImage.SecureUrl.ToString(),
						Code = Guid.NewGuid().ToString(),
					};

					_unitOfWork.StudentRepository.Add(newStudent);
					_unitOfWork.Save();
					TempData["success"] = "Student created successfully";
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["error"] = "Error while creating register";
				return RedirectToAction("Index");
			}

			return View(createStudentViewModel);
		}

		[HttpPost]
		public IActionResult Edit(EditStudentViewModel editStudentViewModel)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var student = _unitOfWork.StudentRepository.Get(s => s.Id == editStudentViewModel.Id);
					student.Name = editStudentViewModel.Name;
					student.LastName = editStudentViewModel.LastName;
					student.Age = DateTime.Now.Year - editStudentViewModel.DateOfBirth.Year;
					student.DateOfBirth = editStudentViewModel.DateOfBirth;
					student.Email = editStudentViewModel.Email;
					student.Phone = editStudentViewModel.Phone;

					_unitOfWork.StudentRepository.Update(student);
					_unitOfWork.Save();
					TempData["success"] = "Student updated successfully";
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["error"] = "Something failed while updating register";
				return RedirectToAction("Index");
			}

			return View(editStudentViewModel);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteStudent(int id)
		{
			var student = _unitOfWork.StudentRepository.Get(s => s.Id == id);
			if(student is  null)
			{
				TempData["error"] = "Student not found";
				return RedirectToAction("Index");
			}

			try
			{
				var deleteImage = await _cloudinaryService.DeletePhoto(student.Image);
				_unitOfWork.StudentRepository.Remove(student);
				_unitOfWork.Save();
				TempData["success"] = "Student deleted successfully";
				return RedirectToAction("Index");
			}catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index");
			}
		}

		#region
		[HttpGet]
		public IActionResult GetAll()
		{
			List<Student> students = _unitOfWork.StudentRepository.GetAll().ToList();
			return Json(new { data = students });
		}
        #endregion
    }
}

SchoolWeb/Controllers/StudyPlanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Domain.Entities;
using School.Infrastructure.Repositories;
using School.Utility;
using SchoolWeb.ViewModels;

namespace SchoolWeb.Controllers
{
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class StudyPlanController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public StudyPlanController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Create()
		{
			List<Subject> subjects = _unitOfWork.SubjectRepository.GetAll().ToList();
			List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();
			CreateStudyPlanViewModel viewModel = new CreateStudyPlanViewModel
			{
				ListSubject = subjects,
				Grades = grades.Select(grade => new SelectListItem { Text = grade.Name, Value = grade.Id.ToString()}).ToList(),
			};

			return View(viewModel);
		}

		public IActionResult Edit(int id)
		{
			List<Subject> subjects = _unitOfWork.SubjectRepository.GetAll().ToList();
			List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();
			StudyPlan studyPlan = _unitOfWork.StudyPlanRepository.Get(studyPlan => studyPlan.Id == id, "Subjects,Grade");
			var subjectSelectedIds = studyPlan.Subjects.Select(x => x.SubjectId.ToString()).ToList();

			EditStudyPlanViewModel editStudyPlanViewModel = new EditStudyPlanViewModel
			{
				ListSubject = subjects.Where(subject => !subjectSelectedIds.Contains(subject.Id.ToString())),
				Grade = new SelectListItem { Text = studyPlan.Grade.Name, Value = studyPlan.Grade.Id.ToString() },
				ListStudyPlanSubject = studyPlan.Subjects,
				GradeId = studyPlan.GradeId,
				Id = studyPlan.Id,
				SubjectIds = string.Join(",", subjectSelectedIds)
			};

			return View(editStudyPlanViewModel);
		}

		[HttpPost]
		public IActionResult Create(CreateStudyPlanViewModel createStudyPlanViewModel)
		{
			if(!ModelState.IsValid)
			{
				List<Subject> subjects = _unitOfWork.SubjectRepository.GetAll().ToList();
				List<Grade> grades = _unitOfWork.GradeRepository.GetAll().ToList();
				CreateStudyPlanViewModel viewModel = new CreateStudyPlanViewModel
				{
					ListSubject = subjects,
					Grades = grades.Select(grade => new SelectListItem { Text = grade.Name, Value = grade.Id.ToString() }).ToList(),
				};

				return View(viewModel);
			}

			var existStudyPlan = _unitOfWork.StudyPlanRepository.Get(studyPlan => studyPlan.GradeId == createStudyPlanViewModel.GradeId);

			if(existStudyPlan is not null)
			{
				TempData["error"] = "There already is a study plan for this grade";
				return RedirectToAction("Index");
			}

			var subjectIds = createStudyPlanViewModel.SubjectIds.Split(",").Select(id => Convert.ToInt32(id));

			foreach (var id in subjectIds)
			{
				var existSubject = _unitOfWork.SubjectRepository.Get(subject => subject.Id == id);

				if(existSubject is null)
				{
					TempData["error"] = "Subject was not found";
					return RedirectToAction("Index");
				}
			}

			using var transaction = _unitOfWork.BeginTransaction();

			try
			{
				var studyPlan = new StudyPlan
				{
					GradeId = createStudyPlanViewModel.GradeId
				};

				_unitOfWork.StudyPlanRepository.Add(studyPlan);
				_unitOfWork.Save();

				foreach (var subject in subjectIds)
				{
					var studyPlanSubject = new StudyPlanSubject
					{
						StudyPlanId = studyPlan.Id,
						SubjectId = subject
					};

					_unitOfWork.StudyPlanSubjectRepository.Add(studyPlanSubject);
					_unitOfWork.Save();
				}

				transaction.Commit();
			}
			catch (Exception ex)
			{
				transaction.Rollback();
				TempData["error"] = "Something failed while creating the study plan";
				return RedirectToAction("Index");
			}
			TempData["success"] = "studyplan created successfully";
			return RedirectToAction("Index");
		}

		#region
		[HttpGet]
		public IActionResult GetAll()
		{
			var studyPlans = _unitOfWork.StudyPlanRepository.GetAll("Subjects,Grade,Subjects.Subject").ToList();
			return Json(new { data = studyPlans });
		}

		[HttpDelete, ActionName("DeleteSubject")]
		public IActionResult Delete(int id)
		{
			try
			{
				var studyPlan = _unitOfWork.StudyPlanSubjectRepository.Get(sp => sp.Id == id);
				_unitOfWork.StudyPlanSubjectRepository.Remove(studyPlan);
				_unitOfWork.Save();
				return Json(new { success = true, message = "Subject deleted successfully", subjectId = studyPlan.SubjectId });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = "Something failed while deleting subject" });
			}
		}

		[HttpDelete, ActionName("Delete")]
		public IActionResult DeleteStudyPlan(int id)
		{
			try
			{
				var studyPlan = _unitOfWork.StudyPlanRepository.Get(sp => sp.Id == id);
				if(studyPlan is null)
				{
					return Json(new { sucess = false, message = "study plan was not found" });
				}
				_unitOfWork.StudyPlanRepository.Remove(studyPlan);
				_unitOfWork.Save();
				return Json(new { success = true, message = "study plan deleted successfully" });
			}catch (Exception ex)
			{
				return Json(new { success = false, message = "something failed while deleting this study plan" });
			}
		}
		#endregion
	}
}

SchoolWeb/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Domain.Entities;
using School.Infrastructure.Repositories;
using School.Utility;
using SchoolWeb.ViewModels;

namespace SchoolWeb.Controllers
{
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class SubjectController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public SubjectController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Create()
		{
			List<Teacher> teachers = _unitOfWork.TeacherRepository.GetAll().ToList();
			List<SelectListItem> teacherList = [];

			foreach(var teacher in teachers)
			{
				teacherList.Add(new SelectListItem { Text = $"{teacher.Name} {teacher.LastName}", Value = teacher.Id.ToString() });
			}

			CreateSubjectViewModel subjectVM = new()
            {
				TeacherLists = teacherList
			};

			return View(subjectVM);
		}

		public IActionResult Detail(int id)
		{
			Subject subject = _unitOfWork.SubjectRepository.Get(subject => subject.Id == id, "Teacher");

			if(subject is null)
			{
				TempData["error"] = "Subject was not found";
				return RedirectToAction("Index");
			}

			return View(subject);
		}

		public IActionResult Edit(int id)
		{
			Subject subject = _unitOfWork.SubjectRepository.Get(subject => subject.Id == id, "Teacher");

			if(subject is null)
			{
                TempData["error"] = "Subject was not found";
                return RedirectToAction("Index");
            }

			List<Teacher> teachers = _unitOfWork.TeacherRepository.GetAll().ToList();
			List<SelectListItem> teacherList = [];

			foreach(var teacher in teachers)
			{
				teacherList.Add(new SelectListItem { Text = $"{teacher.Name} {teacher.LastName}", Value = teacher.Id.ToString() });
			}

			var editSubjectVM = new EditSubjectViewModel
			{
				Id = subject.Id,
				Description = subject.Description,
				Name = subject.Name,
				TeacherId = subject.Teacher.Id,
				TeacherLists = teacherList
			};

			return View(editSubjectVM);
		}

		public IActionResult Delete(int id)
		{
			Subject subject = _unitOfWork.SubjectRepository.Get(subject => subject.Id == id, "Teacher");

			if (subject is null)
			{
				TempData["error"] = "Subject was not found";
				return RedirectToAction("Index");
			}

			return View(subject);
		}

		[HttpPost]
		public IActionResult Create(CreateSubjectViewModel subjectVM)
		{
			try
			{
				if(ModelState.IsValid)
				{
					string code = String.Join("", subjectVM.Name.Split(" "));
					var newSubject = new Subject
					{
						Name = subjectVM.Name,
						Description = subjectVM.Description,
						Code = $"{code.ToUpper()}{DateTime.Now.Year}",
						TeacherId = subjectVM.TeacherId,
					};
					_unitOfWork.SubjectRepository.Add(newSubject);
					_unitOfWork.Save();
					TempData["success"] = "Subject created successfully";
					return RedirectToAction("Index");
				}
			}catch (Exception)
			{
				TempData["error"] = "Error while creating register";
				return RedirectToAction("Index");
			}

			return View(subjectVM);
		}

		[HttpPost]
		public IActionResult Edit(EditSubjectViewModel subjectVM)
		{
			try
			{
				if(ModelState.IsValid)
				{
					var subject = _unitOfWork.SubjectRepository.Get(subject => subject.Id == subjectVM.Id);
					if (subject is null)
					{
						TempData["error"] = "Student not found";
						return RedirectToAction("Index");
					}
					string code = String.Join("", subjectVM.Name.Split(" "));
					subject.Name = subjectVM.Name;
					subject.Description = subjectVM.Description;
					subject.TeacherId = subjectVM.TeacherId;
					subject.Code = $"{code.ToUpper()}{DateTime.Now.Year}";

					_unitOfWork.SubjectRepository.Update(subject);
					_unitOfWork.Save();
					TempData["success"] = "subject updated successfully";
					return RedirectToAction("Index");
				}
			}catch (Exception)
			{
				TempData["error"] = "Error while editing register";
				return RedirectToAction("Index");
			}

			return View(subjectVM);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteSubject(int id)
		{
			var subject = _unitOfWork.SubjectRepository.Get(s => s.Id == id);
			if (subject is null)
			{
				TempData["error"] = "Subject not found";
				return RedirectToAction("Index");
			}

			try
			{
				_unitOfWork.SubjectRepository.Remove(subject);
				_unitOfWork.Save();
				TempData["success"] = "Subject deleted successfully";
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData["error"] = ex.Message;
				return RedirectToAction("Index");
			}
		}


		#region
		[HttpGet]
		public IActionResult GetAll()
		{
			List<Subject> subjects = _unitOfWork.SubjectRepository.GetAll("Teacher").ToList();

			return Json(new { data = subjects });
		}
		#endregion
	}
}

SchoolWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Student" asp-action="Index">Students</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Enrollment" asp-action="Index">Enrollments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="StudyPlan" asp-action="Index">Study Plans</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle  text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    More options
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Grade" asp-action="Index">Grades</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Subject" asp-action="Index">Subjects</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Teacher" asp-action="Index">Teachers</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary">
        <div class="container text-white">
            Made with <i class="bi bi-heart-fill"></i> by Josuedev
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.0.3/js/dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SchoolWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] is not null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]')
	</script>
}

@if (TempData["error"] is not null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]')
	</script>
}